---
title: "Clean and Merge"
author: "Murat Kezer"
output: 
    html_document:
      theme: cerulean
      code_download: TRUE
      toc: TRUE
      toc_float:
        collapsed: FALSE
      toc_depth: 3
      code_folding: hide
---

```{r include=F}
knitr::opts_chunk$set(echo = TRUE, 
                      tidy = TRUE, 
                      cache = FALSE, 
                      warning = FALSE, 
                      message = FALSE)

options(scipen = 999)
```


```{r message = FALSE, results = 'hide'}
library(fs)
library(here)
library(rio)
library(tidyverse)
library(magrittr)
```

# Import data
```{r}
paths <- dir_ls(here("data"))
df_names <- gsub(".+data/(.+)\\.sav", "\\1", paths)

walk2(df_names, paths, ~{
  assign(.x, import(.y), envir = .GlobalEnv)
})
```

# Make variable types/names congruent for merging
```{r}
# rename
ind_diffs_self %<>% 
  rename(PerUn = SubNum)

old_names <- names(raw_informant_data[,44:189])
new_names <- paste0(names(raw_informant_data[, 44:189]), "_inf")

raw_informant_data %<>% 
  rename_at(vars(old_names), ~ new_names)

# remove
ind_diffs_self %<>% 
  select(-sex:-strait26,
         -Perceiver, -Target)

raw_informant_data %<>% 
  select(-Perceiver,
         -name:-V3)

# bfi
informant_bfi <- 
  raw_informant_data %>% 
  select(PerUn, starts_with("bfi")) %>% 
    group_by(PerUn) %>% 
    summarise(across(bfi1:bfi26, 
                     mean, na.rm = TRUE)
              ) %>% 
    ungroup() %>% 
    rename_at(vars(bfi1:bfi26), ~ paste0("itrait", 1:26)
              )
```

# Merge
```{r}
df <- list(perceiver_target_data,
           perceiver_target_affect_EA,
           ind_diffs_self,
           informant_bfi,
           aggregated_informant_data) %>% 
  reduce(left_join)

rm(list = gdata::keep(df))
```

# Clean and rename variables
```{r}

source("functions.R")


```











































